const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const app = express();
app.use(cors());
app.use(express.json());
mongoose.connect(process.env.MONGO_URI||'mongodb://localhost:27017/hardwareshop')
.then(()=>console.log('MongoDB connected'))
.catch(err=>console.log(err));
const Product=require('./Product');
const Customer=require('./Customer');
const Bill=require('./Bill');
const Vendor=require('./Vendor');
const r=require('express').Router;
const pr=r(),cr=r(),br=r(),vr=r();
pr.get('/',async(req,res)=>{try{res.json(await Product.find().sort({createdAt:-1}))}catch(e){res.status(500).json({error:e.message})}});
pr.post('/',async(req,res)=>{try{res.status(201).json(await new Product(req.body).save())}catch(e){res.status(400).json({error:e.message})}});
pr.put('/:id',async(req,res)=>{try{res.json(await Product.findByIdAndUpdate(req.params.id,req.body,{new:true}))}catch(e){res.status(400).json({error:e.message})}});
pr.delete('/:id',async(req,res)=>{try{await Product.findByIdAndDelete(req.params.id);res.json({message:'Deleted'})}catch(e){res.status(500).json({error:e.message})}});
cr.get('/',async(req,res)=>{try{res.json(await Customer.find().sort({createdAt:-1}))}catch(e){res.status(500).json({error:e.message})}});
cr.post('/',async(req,res)=>{try{res.status(201).json(await new Customer(req.body).save())}catch(e){res.status(400).json({error:e.message})}});
cr.delete('/:id',async(req,res)=>{try{await Customer.findByIdAndDelete(req.params.id);res.json({message:'Deleted'})}catch(e){res.status(500).json({error:e.message})}});
br.get('/',async(req,res)=>{try{res.json(await Bill.find().sort({createdAt:-1}))}catch(e){res.status(500).json({error:e.message})}});
br.post('/',async(req,res)=>{try{const{customer,items,total,date}=req.body;for(const item of items){await Product.findByIdAndUpdate(item.productId,{$inc:{stock:-item.qty}})}res.status(201).json(await new Bill({customer,items,total,date}).save())}catch(e){res.status(400).json({error:e.message})}});
br.delete('/:id',async(req,res)=>{try{await Bill.findByIdAndDelete(req.params.id);res.json({message:'Deleted'})}catch(e){res.status(500).json({error:e.message})}});
vr.get('/',async(req,res)=>{try{res.json(await Vendor.find().sort({createdAt:-1}))}catch(e){res.status(500).json({error:e.message})}});
vr.post('/',async(req,res)=>{try{res.status(201).json(await new Vendor(req.body).save())}catch(e){res.status(400).json({error:e.message})}});
vr.delete('/:id',async(req,res)=>{try{await Vendor.findByIdAndDelete(req.params.id);res.json({message:'Deleted'})}catch(e){res.status(500).json({error:e.message})}});
app.use('/api/products',pr);
app.use('/api/customers',cr);
app.use('/api/bills',br);
app.use('/api/vendors',vr);
app.get('/',(req,res)=>res.send('OK'));
app.listen(process.env.PORT||5000,()=>console.log('Server running'));
